from pyspark.sql import SparkSession
from pyspark.sql.window import Window
from pyspark.sql.functions import *
from datetime import datetime
import time

from dependencies.utilities import *



def run(spark: SparkSession, config_dict: dict, module: str, sub_module: str, job: str, full_refresh: int = 0):
    print(f"Running {module}.{sub_module}.{job}")
    trigger_time = datetime.now()
    start_time = time.time()
    try:
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_ds ALTER COLUMN `DSContactID` COMMENT 'Identifier for merged Location';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_ds ALTER COLUMN `FirstName` COMMENT 'Contact First Name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_ds ALTER COLUMN `LastName` COMMENT 'Contact Last Name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_ds ALTER COLUMN `EmailAddress` COMMENT 'Contact Email Address';")

        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `ContactKey` COMMENT 'Unique Contact Code/Identifier (ClCont.ContactKey)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `BaseLocation` COMMENT 'Main location for Contact (ref dim_location_dse.Location)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `IsSlug` COMMENT 'Y/N indicator for a Slug contact.  Typically N';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `PreName` COMMENT 'Name Prefix/Title (e.g. Mr., Mrs., Dr.)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `FirstName` COMMENT 'Contact First Name (formal)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `MiddleName` COMMENT 'Contact Middle Name/Initial';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `LastName` COMMENT 'Contact Last Name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `Suffix` COMMENT 'Contact Suffix (e.g. Jr., Sr., RN, MD)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `Salutation` COMMENT 'Contact First/NickName';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `JobCd` COMMENT 'Contact Job/Occupation Code (~80 codes total)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `JobCdDescription` COMMENT 'Contact Job Description (for JobCode)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `PhoneAccess` COMMENT 'Phone Prefix/Country Code (typically 1)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `PhoneAreaCode` COMMENT 'Phone Area Code';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `Phone` COMMENT 'Phone core number (7 digit no hyphen)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `PhoneExt` COMMENT 'Phone Extension';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `DateCreated` COMMENT 'Date and time record created';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `DateUpdated` COMMENT 'Date and time record last updated';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `PersonID` COMMENT 'Alternate identifier field for contact';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `EmailAddress` COMMENT 'Contact email address (if known)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `DSContactID` COMMENT 'Calculated reference to combined Contact (ref dim_contact_ds)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `Status` COMMENT 'Contact Status (Active/Inactive)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `JobBucketCd` COMMENT 'Job Bucket Code.  Coalesce Job Code/Desc to one of 14 buckets';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `JobBucket` COMMENT 'Job Bucket Name (e.g. Nursing, Maintenance, Administrator)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dse ALTER COLUMN `JobTitle` COMMENT 'Contact Job Description (free form)';")

        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dssi ALTER COLUMN `CustCode` COMMENT 'DSSI Provider Code (ref dim_location_dssi)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dssi ALTER COLUMN `CustLocNum` COMMENT 'DSSI Customers Location Number (ref dim_location_dssi)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dssi ALTER COLUMN `CustContNum` COMMENT 'Unique integer identifier for Contact';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dssi ALTER COLUMN `Username` COMMENT 'Unique username within Provider';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dssi ALTER COLUMN `FirstName` COMMENT 'Persons first name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dssi ALTER COLUMN `LastName` COMMENT 'Persons last name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dssi ALTER COLUMN `DSSIDSEContactKey` COMMENT 'Optional reference to DSE Contact (ref dim_contact_dse.ContactKey)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dssi ALTER COLUMN `JobCd` COMMENT 'DSSI Job Code';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dssi ALTER COLUMN `Active` COMMENT 'Login enabled (Y/N)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dssi ALTER COLUMN `TestFlag` COMMENT 'Test/Production status code - test accounts cannot order (T/P)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dssi ALTER COLUMN `EmailAddress` COMMENT 'Persons email address';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dssi ALTER COLUMN `Created` COMMENT 'Date and time record was created';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dssi ALTER COLUMN `CreatedBy` COMMENT 'DS employees login for who created';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dssi ALTER COLUMN `ContactGrp` COMMENT 'Calculated code to define contact groups.  Accounts for DSSI master contacts.';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_contact_dssi ALTER COLUMN `DSContactID` COMMENT 'Calculated code:  use if valid DSSIDSEContactKey, else CustContNum (ref dim_contact_ds.DSContactID)';")

        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `Date` COMMENT 'Date';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `BusDay#ofMo` COMMENT 'Business Day of Month (bus days on/before date in current month)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `BusDay#ofQtr` COMMENT 'Business Day of Quarter (bus days on/before date in current quarter)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `BusDay#ofYear` COMMENT 'Business Day of Year (bus days on/before date in current year)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `IsBOM` COMMENT 'Is date the beginning of month';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `IsEOM` COMMENT 'Is date the end of the month';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `IsHoliday` COMMENT 'Is date a holiday';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `IsBudgetException` COMMENT 'Is date excluded from budget (sales)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `BegOfMonthDate` COMMENT 'Date of the beginning of the current month (e.g. 1/1, 2/1)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `EndOfMonthDate` COMMENT 'Date of the end of the current month (e.g. 1/31, 2/28)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `BusBegOfMonthDate` COMMENT 'Date of the first business day in current month';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `BusEndOfMonthDate` COMMENT 'Date of the last business day in current month';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `Day#ofWeek` COMMENT 'Day of week (Sunday = 1, etc.)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `Day#ofMo` COMMENT 'Month day';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `Day#ofYear` COMMENT 'Day of year (days on/before date in current year)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `Week#` COMMENT 'Calendar week number of year (partial first week common)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `Month#` COMMENT 'Month number of year (1-12)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `Quarter#` COMMENT 'Quarter number of year (1-4)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `IsBusinessDay` COMMENT 'Is date a business day for Direct Supply';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `Year` COMMENT 'Year Number';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `Weekday` COMMENT 'Day of Week';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_date ALTER COLUMN `Month` COMMENT 'Month Name';")

        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_ds ALTER COLUMN `DSLocationID` COMMENT 'Identifier for merged Location';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_ds ALTER COLUMN `LocName` COMMENT 'Location Name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_ds ALTER COLUMN `AddressLine1` COMMENT 'Location Address Line 1';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_ds ALTER COLUMN `AddressLine2` COMMENT 'Location Address Line 2';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_ds ALTER COLUMN `City` COMMENT 'Location City';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_ds ALTER COLUMN `State` COMMENT 'Location State';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_ds ALTER COLUMN `Zip` COMMENT 'Location Zip';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_ds ALTER COLUMN `PhoneAreaCode` COMMENT 'Phone Area Code';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_ds ALTER COLUMN `Phone` COMMENT 'Phone Number (7 digit no dashes)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_ds ALTER COLUMN `PhoneExt` COMMENT 'Optional Phone Extension';")

        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `Location` COMMENT 'Unique location code/identifier (ClLocn.Location)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocStatusCd` COMMENT 'Location Status (ClLocn.Status)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `CorpLocation` COMMENT 'Corporate Location Code (ClLocn.CorpLocation, self ref)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `OwnManageLease` COMMENT 'Own/Manage/Lease Code (ClLocn.OwnManageLease)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `OwnerLocation` COMMENT 'Owner Location Code (ClLocn.OwnerLocation, self ref)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `DSELocName` COMMENT 'Location Name (ClLocn.Name)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `AddressLine1` COMMENT 'Location Address Line #1 (ClLocn.AddressLine1)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `AddressLine2` COMMENT 'Location Address Line #2 (ClLocn.AddressLine2).  Optional';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `City` COMMENT 'Location City (ClLocn.City)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `State` COMMENT 'Location State (ClLocn.State)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `Zip` COMMENT 'Location Zip (ClLocn.Zip)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `Country` COMMENT 'Location Country (ClLocn.Country)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `PhoneAreaCode` COMMENT 'Phone Area Code (ClLocn.PhoneAreaCode)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `Phone` COMMENT 'Phone Number (ClLocn.Phone, e.g. 555-5555)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `PhoneExt` COMMENT 'Optional Phone Extension (ClLocn.PhoneExtension)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `CreatedDate` COMMENT 'When Location was created.  Null if unknown (ClLocn.CreateDate)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `UpdatedDate` COMMENT 'When Location was last updated (ClLocn.DateUpdated)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocTypeCd` COMMENT 'Location Type Code (many similar to MarketCd)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocType` COMMENT 'Location Type Name (many, similar to Market)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `DivisionCd` COMMENT 'Location Division Code (I,C)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `Division` COMMENT 'Location Division Name (Independent, Corporate)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `MarketCd` COMMENT 'Location Market Code (AL, AM, XN, SN, AC)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `Market` COMMENT 'Location Market Name (Senior Living, Ambulatory, Special Market, Skilled Nursing, Acute)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `ForProfitCd` COMMENT 'For Profit Code (F, N, C, blank)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `ForProfit` COMMENT 'For Profit Name (For Profit, Not For Profit, Non-Profit, Unknown)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `CorpLocationNm` COMMENT 'Corporation Location Name (via CorpLocation)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocCorpContractCd` COMMENT 'Corporate Contract Code';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocCorpContractNm` COMMENT 'Corporate Contract Name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocCorpContractPriceClass` COMMENT 'Corporate Contract Price Class Code';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocCorpContractBaseClass` COMMENT 'Corporate Contract Base Class (Level A, B, C D)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocGPOContractCd` COMMENT 'GPO Contract Code (optional)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocGPOContractPriceClass` COMMENT 'GPO Contract Price Class Code (optional)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocGPOContractBaseClass` COMMENT 'GPO Contract Base Class (Level A, B, C D) (optional)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `DSLocationID` COMMENT 'Calculated reference to combined Location (ref dim_location_ds)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `AcuteCareBedCnt` COMMENT 'Number of beds for Acute Care';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `AlzheimersBedCnt` COMMENT 'Number of beds for Alzheimers';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `AssistedLivingBedCnt` COMMENT 'Number of beds for Assisted Living';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `HospiceBedCnt` COMMENT 'Number of beds for Hospice';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `IndependentLivingBedCnt` COMMENT 'Number of beds for Independent Living';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `IntermediateCareBedCnt` COMMENT 'Number of beds for Intermediate Care';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LongTermCareSkilledNursingBedCnt` COMMENT 'Number of beds for Long Term Care/Skilled Nursing';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `OtherBedCnt` COMMENT 'Number of beds for Other purposes';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `SubacuteCareBedCnt` COMMENT 'Number of beds for Subacute Care';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `TotalBedCnt` COMMENT 'Number of all beds at Location';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `OwnerLocationNm` COMMENT 'Owning Location Name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocGPOContractNm` COMMENT 'GPO Contract Name (optional)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `Location` COMMENT 'Unique location code/identifier (ClLocn.Location)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocStatusCd` COMMENT 'Location Status (ClLocn.Status)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `CorpLocation` COMMENT 'Corporate Location Code (ClLocn.CorpLocation, self ref)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `OwnManageLease` COMMENT 'Own/Manage/Lease Code (ClLocn.OwnManageLease)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `OwnerLocation` COMMENT 'Owner Location Code (ClLocn.OwnerLocation, self ref)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `DSELocName` COMMENT 'Location Name (ClLocn.Name)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `AddressLine1` COMMENT 'Location Address Line #1 (ClLocn.AddressLine1)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `AddressLine2` COMMENT 'Location Address Line #2 (ClLocn.AddressLine2).  Optional';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `City` COMMENT 'Location City (ClLocn.City)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `State` COMMENT 'Location State (ClLocn.State)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `Zip` COMMENT 'Location Zip (ClLocn.Zip)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `Country` COMMENT 'Location Country (ClLocn.Country)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `PhoneAreaCode` COMMENT 'Phone Area Code (ClLocn.PhoneAreaCode)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `Phone` COMMENT 'Phone Number (ClLocn.Phone, e.g. 555-5555)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `PhoneExt` COMMENT 'Optional Phone Extension (ClLocn.PhoneExtension)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `CreatedDate` COMMENT 'When Location was created.  Null if unknown (ClLocn.CreateDate)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `UpdatedDate` COMMENT 'When Location was last updated (ClLocn.DateUpdated)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocTypeCd` COMMENT 'Location Type Code (many similar to MarketCd)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocType` COMMENT 'Location Type Name (many, similar to Market)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `DivisionCd` COMMENT 'Location Division Code (I,C)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `Division` COMMENT 'Location Division Name (Independent, Corporate)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `MarketCd` COMMENT 'Location Market Code (AL, AM, XN, SN, AC)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `Market` COMMENT 'Location Market Name (Senior Living, Ambulatory, Special Market, Skilled Nursing, Acute)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `ForProfitCd` COMMENT 'For Profit Code (F, N, C, blank)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `ForProfit` COMMENT 'For Profit Name (For Profit, Not For Profit, Non-Profit, Unknown)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `CorpLocationNm` COMMENT 'Corporation Location Name (via CorpLocation)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocCorpContractCd` COMMENT 'Corporate Contract Code';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocCorpContractNm` COMMENT 'Corporate Contract Name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocCorpContractPriceClass` COMMENT 'Corporate Contract Price Class Code';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocCorpContractBaseClass` COMMENT 'Corporate Contract Base Class (Level A, B, C D)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocGPOContractCd` COMMENT 'GPO Contract Code (optional)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocGPOContractPriceClass` COMMENT 'GPO Contract Price Class Code (optional)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocGPOContractBaseClass` COMMENT 'GPO Contract Base Class (Level A, B, C D) (optional)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `DSLocationID` COMMENT 'Calculated reference to combined Location (ref dim_location_ds)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `AcuteCareBedCnt` COMMENT 'Number of beds for Acute Care';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `AlzheimersBedCnt` COMMENT 'Number of beds for Alzheimers';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `AssistedLivingBedCnt` COMMENT 'Number of beds for Assisted Living';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `HospiceBedCnt` COMMENT 'Number of beds for Hospice';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `IndependentLivingBedCnt` COMMENT 'Number of beds for Independent Living';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `IntermediateCareBedCnt` COMMENT 'Number of beds for Intermediate Care';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LongTermCareSkilledNursingBedCnt` COMMENT 'Number of beds for Long Term Care/Skilled Nursing';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `OtherBedCnt` COMMENT 'Number of beds for Other purposes';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `SubacuteCareBedCnt` COMMENT 'Number of beds for Subacute Care';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `TotalBedCnt` COMMENT 'Number of all beds at Location';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `OwnerLocationNm` COMMENT 'Owning Location Name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse ALTER COLUMN `LocGPOContractNm` COMMENT 'GPO Contract Name (optional)';")

        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `CustCode` COMMENT 'DSSI Provider Code';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `CustLocNum` COMMENT 'DSSI Customers Location Number/Code';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `FacilityKey` COMMENT 'DSSI Location Identifier';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `Status` COMMENT 'Location Active Status/Type (A, I, S, T)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `DSSIDSELocation` COMMENT 'Optional reference to DSE Location (ref dim_location_dse.Location)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `DSSILocName` COMMENT 'Location Name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `AddressLine1` COMMENT 'Location Address Line 1';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `AddressLine2` COMMENT 'Location Address Line 2';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `City` COMMENT 'Location City';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `State` COMMENT 'Location State';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `Zip` COMMENT 'Location Zip';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `PhoneAccess` COMMENT 'Phone Prefix/Country Code (typically 1)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `PhoneAreaCode` COMMENT 'Phone Area Code';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `Phone` COMMENT 'Phone Number (7 digit no dashes)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `PhoneExt` COMMENT 'Optional Phone Extension';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `KeepActive` COMMENT 'Y/N indicator, once used for DSE link';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `LiveDate` COMMENT 'Date location can begin ordering (go live)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `LocTestFlag` COMMENT 'Test flag code for prod/test  (P, T)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `LocType` COMMENT 'Code for position in location hierarchy (3=corp, 2=division,1=region,0=fac)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `CreatedDate` COMMENT 'When record was created';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `DSLocationID` COMMENT 'Calculated code:  use DSSIDSELocation if valid, else CustCode.CustLocNum (ref dim_location_ds)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `TotalBedCnt` COMMENT 'Number of all beds at Location';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `CustCode` COMMENT 'DSSI Provider Code';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `CustLocNum` COMMENT 'DSSI Customers Location Number/Code';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `FacilityKey` COMMENT 'DSSI Location Identifier';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `Status` COMMENT 'Location Active Status/Type (A, I, S, T)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `DSSIDSELocation` COMMENT 'Optional reference to DSE Location (ref dim_location_dse.Location)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `DSSILocName` COMMENT 'Location Name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `AddressLine1` COMMENT 'Location Address Line 1';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `AddressLine2` COMMENT 'Location Address Line 2';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `City` COMMENT 'Location City';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `State` COMMENT 'Location State';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `Zip` COMMENT 'Location Zip';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `PhoneAccess` COMMENT 'Phone Prefix/Country Code (typically 1)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `PhoneAreaCode` COMMENT 'Phone Area Code';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `Phone` COMMENT 'Phone Number (7 digit no dashes)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `PhoneExt` COMMENT 'Optional Phone Extension';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `KeepActive` COMMENT 'Y/N indicator, once used for DSE link';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `LiveDate` COMMENT 'Date location can begin ordering (go live)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `LocTestFlag` COMMENT 'Test flag code for prod/test  (P, T)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `LocType` COMMENT 'Code for position in location hierarchy (3=corp, 2=division,1=region,0=fact)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `CreatedDate` COMMENT 'When record was created';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `DSLocationID` COMMENT 'Calculated code:  use DSSIDSELocation if valid, else CustCode.CustLocNum (ref dim_location_ds)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dssi ALTER COLUMN `TotalBedCnt` COMMENT 'Number of all beds at Location';")

        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_order_dse_channel ALTER COLUMN `OrderChannelCd` COMMENT 'Ordering Channel Code used when placing the order';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_order_dse_channel ALTER COLUMN `OrderChannelDesc` COMMENT 'No comment';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_order_dse_channel ALTER COLUMN `OrderChannelGroupDesc` COMMENT 'No comment';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_order_dse_channel ALTER COLUMN `OrderChannelSubGroupDesc` COMMENT 'No comment';")


        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_order_dse_lob ALTER COLUMN `LineOfBusinessCurrentKey` COMMENT 'Generated Identifier';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_order_dse_lob ALTER COLUMN `LOBCd` COMMENT 'Line of Business Code (01, 02, etc.)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_order_dse_lob ALTER COLUMN `LOB` COMMENT 'Line of Business Name (Aptura, Supply, Capital, etc.)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_order_dse_lob ALTER COLUMN `LOBGroupCd` COMMENT 'Line of Business Group Code (A, B, etc.)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_order_dse_lob ALTER COLUMN `LOBGroup` COMMENT 'Line of Business Group Name (Products, Services, etc.)';")

        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductCurrentKey` COMMENT 'Product source identifier (DimProductCurrent.ProductCurrentKey)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductNbr` COMMENT 'DS (categorized) or Supplier (non-categorized) product number';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductSegmentId` COMMENT 'DS product segment identifier (first category tier)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductSegment` COMMENT 'DS product segment name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductProgramId` COMMENT 'DS product program identifier (second category tier)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductProgram` COMMENT 'DS product program name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductSubGroupId` COMMENT 'DS product sub group identifier (third category tier)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductSubGroup` COMMENT 'DS product sub group name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductPriceFamily` COMMENT 'DS product price family.  Similar to product model name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductType` COMMENT 'DS product type';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductSubType` COMMENT 'DS product sub-type';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductPreFlatNbr` COMMENT 'DS product number before prem flattening (delineates similar products)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductDesc` COMMENT 'Line/Product description';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `SupplierCd` COMMENT 'Supplier Code';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `SupplierNm` COMMENT 'Supplier Name';")

        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductCurrentKey` COMMENT 'Product source identifier (DimProductCurrent.ProductCurrentKey)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductNbr` COMMENT 'DS (categorized) or Supplier (non-categorized) product number';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductSegmentId` COMMENT 'DS product segment identifier (first category tier)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductSegment` COMMENT 'DS product segment name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductProgramId` COMMENT 'DS product program identifier (second category tier)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductProgram` COMMENT 'DS product program name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductSubGroupId` COMMENT 'DS product sub group identifier (third category tier)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductSubGroup` COMMENT 'DS product sub group name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductPriceFamily` COMMENT 'DS product price family.  Similar to product model name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductType` COMMENT 'DS product type';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductSubType` COMMENT 'DS product sub-type';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductPreFlatNbr` COMMENT 'DS product number before prem flattening (delineates similar products)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `ProductDesc` COMMENT 'Line/Product description';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `SupplierCd` COMMENT 'Supplier Code';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_product_dse ALTER COLUMN `SupplierNm` COMMENT 'Supplier Name';")

        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_activity_dssmart ALTER COLUMN `Location` COMMENT 'DSE Location Code (ref dim_location_dse.Location)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_activity_dssmart ALTER COLUMN `Date` COMMENT 'Event Date (ref dim_date.Date)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_activity_dssmart ALTER COLUMN `VitalsDSSmart` COMMENT 'Count of Vital Submissions taken';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_activity_dssmart ALTER COLUMN `LoginsDSSmart` COMMENT 'No comment';")

        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_login_tels ALTER COLUMN `Location` COMMENT 'TELS login Location (ref dim_location_dse)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_login_tels ALTER COLUMN `ContactKey` COMMENT 'Person/Customer who placed order (ref dim_contact_dse)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_login_tels ALTER COLUMN `Date` COMMENT 'TELS login Date (ref dim_date.Date)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_login_tels ALTER COLUMN `LoginTELS` COMMENT 'Count of TELS logins (any)';")

        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dse ALTER COLUMN `LineId` COMMENT 'Line source identifier (TrLines.LineID)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dse ALTER COLUMN `OrderDate` COMMENT 'Date order was placed (ref dim_date)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dse ALTER COLUMN `Location` COMMENT 'Order Location (ref dim_location_dse)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dse ALTER COLUMN `ContactKey` COMMENT 'Person/Customer who placed order (ref dim_contact_dse)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dse ALTER COLUMN `LineOfBusinessCurrentKey` COMMENT 'Order Line of Business (ref dim_order_dse_lob)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dse ALTER COLUMN `OrderChannelCd` COMMENT 'Ordering channel used to place order (ref dim_order_dse_channel)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dse ALTER COLUMN `ProductCurrentKey` COMMENT 'Product ordered (ref dim_product_dse)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dse ALTER COLUMN `OrderCancelled` COMMENT 'Is Order Canceled';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dse ALTER COLUMN `OrderNbr` COMMENT 'Order Number';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dse ALTER COLUMN `OrderWhen` COMMENT 'Date and Time order was placed';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dse ALTER COLUMN `LineQty` COMMENT 'Line units ordered';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dse ALTER COLUMN `LineUnitSell` COMMENT 'Line sell price per unit';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dse ALTER COLUMN `LineAmount` COMMENT 'Total line amount (LineQty*LineUnitSell + line charges)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dse ALTER COLUMN `LineUMCd` COMMENT 'Unit of measure (e.g. case, each)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dse ALTER COLUMN `OrderCorpContractCd` COMMENT 'Contract Code at time of order';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dse ALTER COLUMN `OrderCorpContractNm` COMMENT 'Contract Name at time of order';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dse ALTER COLUMN `OrderGPOContractCd` COMMENT '(Optional) GPO Contract Code at time of order';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dse ALTER COLUMN `OrderGPOContractNm` COMMENT '(Optional) GPO Contract Name at time of order';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dse ALTER COLUMN `ContractedProduct` COMMENT 'Contracted product (price) at time of order';")

        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dssi ALTER COLUMN `CustCode` COMMENT 'DSSI Provider Code (ref dim_location_dssi)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dssi ALTER COLUMN `CustLocNum` COMMENT 'DSSI Customers Location Number/Code (ref dim_location_dssi)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dssi ALTER COLUMN `FacilityKey` COMMENT 'DSSI Facility Key (ref dim_location_dssi)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dssi ALTER COLUMN `CustContNum` COMMENT 'DSSI Contact Identifier (ref dim_contact_dssi.CustContNum)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dssi ALTER COLUMN `Date` COMMENT 'Order Date (ref dim_date.Date)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dssi ALTER COLUMN `POCancelled` COMMENT 'Canceled indicator';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dssi ALTER COLUMN `PONbr` COMMENT 'DSSI Purchase Order Number (with credit logic)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dssi ALTER COLUMN `LinePoNbr` COMMENT 'DSSI Source system key/Orig PO Number (chlines.chponum)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dssi ALTER COLUMN `LineNbr` COMMENT 'DSSI Source system key/Line Number (chlines.AccLineNum)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dssi ALTER COLUMN `LineQty` COMMENT 'Quantity Ordered';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dssi ALTER COLUMN `LineUnitSell` COMMENT 'Sell price of item';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dssi ALTER COLUMN `LineAmount` COMMENT 'Total Line Amount (Qty*UnitSell) plus any line charges';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dssi ALTER COLUMN `LineUMCd` COMMENT 'Unit of Measure ordered (CA for Case, EA for Each, etc.)';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dssi ALTER COLUMN `ProductNbr` COMMENT 'Suppliers Product Number for item';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dssi ALTER COLUMN `ProductDesc` COMMENT 'Product/Item Description';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dssi ALTER COLUMN `SupplierCd` COMMENT 'DSSIs Supplier (Distribution center) Code';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dssi ALTER COLUMN `SupplierName` COMMENT 'DSSIs Supplier (Distribution center) Name';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dssi ALTER COLUMN `ParentSupplierCd` COMMENT 'DSSI Corp Supplier Code';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.fact_order_dssi ALTER COLUMN `ParentSupplierName` COMMENT 'DSSI Corp Supplier Name';")

        # dim_location_dse
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse CHANGE `MarketCd` `MarketCd` string COMMENT 'The market code of the location. 'AL'='Assisted Living', 'SN'='Skilled Nursing', 'XN'='Special Markets'. This is Marketing's view of the market. It is a grouping of Location Type, which is assigned by the Customer Database team';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse CHANGE `Market` `Market` string COMMENT 'The market name of the location. Values include: 'Assisted Living', 'Skilled Nursing', 'Special Markets'. This is Marketing's view of the market. It is a grouping of Location Type, which is assigned by the Customer Database team';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse CHANGE `CreditStatusDesc` `CreditStatusDesc` string COMMENT 'The location's Financial Credit Status';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse CHANGE `AccountManagerDivisionNm` `AccountManagerDivisionNm` string COMMENT 'The division name of the account manager currently assigned to the location by Sales Ops';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse CHANGE `AccountManagerTeamNm` `AccountManagerTeamNm` string COMMENT 'The team name of the account manager currently assigned to the location by Sales Ops';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse CHANGE `AccountManagerNm` `AccountManagerNm` string COMMENT 'The name of the account manager currently assigned to the location by Sales Ops';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse CHANGE `CapitalSalesConsultantTeamNm` `CapitalSalesConsultantTeamNm` string COMMENT 'The team name of the capital sales consultant currently assigned to the location by Sales Ops';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse CHANGE `CapitalSalesConsultantNm` `CapitalSalesConsultantNm` string COMMENT 'The capital sales consultant name currently assigned to the location by Sales Ops';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse CHANGE `NationalAccountManagerTeamNm` `NationalAccountManagerTeamNm` string COMMENT 'The team name of the national account manager currently assigned to the location by Sales Ops';")
        spark.sql("ALTER TABLE app_dsi_datastitching.default.dim_location_dse CHANGE `NationalAccountManagerNm` `NationalAccountManagerNm` string COMMENT 'The name of the national account manager currently assigned to the location by Sales Ops';")

        print(f"{'/-'*40}")
        print(f"{'--'*40}")
    except Exception:
        end_time = time.time()
        elapsed_time = end_time - start_time
        exc_type, exc_msg, stack_trace = get_sys_exception()
        print(f"{module}.{sub_module}.{job} job failed")
        print(f"{'/-'*10} Exception Type {'/-'*10}")
        print(exc_type)
        print(f"{'/-'*10} Exception Message {'/-'*10}")
        print(exc_msg)
        print(f"{'/-'*10} Stack Trace {'/-'*10}")
        print(stack_trace)
        spark.stop()
    else:     
        end_time = time.time()
        elapsed_time = end_time - start_time
        print(f"{module}.{sub_module}.{job} job ran successfully.")
    finally:
        print(f"Execution of {module}.{sub_module}.{job} job took {elapsed_time} seconds")